<!DOCTYPE html>
<html>
<head>
	<title>Laying the path</title>
</head>
<body>
	<p>
		I never really had a formal training in mathematics - what I mean is that I went through school, calculus, linear algebra, insofar as a body of work, but did not get into the solid confidence of proofs and set notation until this semester. Life just had not exposed me to it, and I had been busy with other hobby avenues. Proofs in highschool and prior were just kind of "yes, that makes sense, I suppose it's true", as many would also do. But I did want more. And, thankfully, this semester in graduate school somehow had me in the Courant Institute of Mathematical Science, where my algorithms recitation leader entertained a discussion about how we know a solution is 1) correct and 2) the most efficient.
	</p>
	<p>
		The first criterion is a fair bit easier than the second. Correctness is often proven by induction, or a logical cascade of "if this is true, then the surrounding conditions are also true, ad infinitum". In computer science, this can be abstracted as a loop invariant. If there are no counterexamples, then correctness is proven. I have had difficulties thinking of counterexamples. My whole life has been somewaht Bayesian: "this approach usually and generally works" and 99% of the time it does. I guess you would call this probabilistic programming. But with algorithms that just wouldn't fly, and I was grounded for a time along with it. We needed it to be irrefutably proper and working, not for just test cases but for all. And practically so. So proofs were important. 
	</p>
	<p>
		Given this self-realization that most of my life has been based on general consolidation and integration of ideas, reinforcement, basic "checksums", and digestion of thousands of stories, I figured it would behoove me to apply proofs to my behaviors. And if they are wrong, I will change them. Obviously I can't do this for everything: some things are so irreducably complex in the human eye that thinking of a loop invariant for them is an NP-hard task. That is, we shouldn't even think about it if we want to spend our time beyond that thinking. What I will do, though, is apply principles similar to a book I read in senior year of undergraduate studies, which applied computer science principles to life, such as when to date, how much to explore, and so on based on mathematical pillars. This was before my advanced computer science education, so now I have a greater foothold to write about it myself.    
	</p>
	<p>
		Let's start off with the ultimate meaning. If I can apply induction on this, I'll be a lot more confident that all the other approaches moving toward it are actually worth their time. First a story to lead in: In the mornings before school, I would wake up at around 5:50am, which is definitely not the earliest time of heard of. In that hour I would eat breakfast, sometimes shower, always dress, and use the bathroom. The bathroom was a source of anxiety if I felt anal retentive and if the time to depart overlapped with my not yet accomplishing my bodily executions. Else, I would feel the pressure the whole day, writhing in my seat wondering why I would be subjecting to the whims of such a volatile feeling. (These days, I even use a portable bidet, compensating for horrors past). Anyways, during this time on the 'plopper', as kids put it, I would venture into the territory not as a teen as I was, but instead of what the meaning of life was. I don't know why that was the time to do it, but that's how it unfolded. Upon that throne I thought about many things until my thighs were marked with two red circles, one from each elbow as The Thinker possessed me. I once eventually decided the meaing was happiness. The apocryphal Mark Twain quote 'When I grow up, I want to be happy,' was a main fixture of the philosophy.  
	</p>
	<p>
		Since then, I've found myself deviating from that single ideological pillar of happiness at least in practice - we can imagine the case of the Matrix where if given the option to be pumped with dopamine (happiness), would we do it? One may argue happiness is more nuanced and irreducable, but insofar as our cardinal definition of happiness, it is dopamine. So then, yes, when we talk of happiness, as long as I'm not a quest for cocaine, I mean something else. I mean to indicate a deeper type of growth, but I'm really not sure what, as most of us can also empathize with. Meaningful relationships die, along with the people that they connect. Not to say that's not something I have on my checklist, but I look further. We have a counterexample that demonstrates that pure happiness is not something a lot of us would want. 
	</p>
	<p>
		The next subject of consideration I came to was that there is only one life for certain in this universe (all potential beliefs aside which grant more, who may be true but are still less certain). This is important - life is as much an experience as it is a single one-off "pilot" opportunity that allows for at least a semblance of free will. Given that, more emphasis is given on mobility, opportunity, and design rather than a simple happiness optimization routine in a given socioeconomic class (low to high classes may satisfy that with daily Netflix and revelry, while high classes can satisfy that with just as expendable experiences such as travel and luxury). This I think is the prime difference between what many conclude as a "make your bed and settle down"-type plan, since if we induct that, it is simply generations of the same. And of course, even with a life more energized plan, settling down is still an option in later years. 
	</p>
	<p>
		This can be considered the main controversial turning point I hope to finally iron out through more explained rigor here. In high school one of my main adages when studying for tests and dotting every i was the thought "this is for your children". It is a wonderful thing to want the best life for your future children, and therefore first a high-income correlated life was the target. This parental drive I probably should have written about in my college application essays. However, somewhere later along the line of cynicism, I corrected myself: what will increasing income other than create cone-visioned offspring that don't really relate to others (either in a bubble or spoiled) and may potentially make others sad themselves (by comparison)? For a further explanation, imagine we want the best for our families - in this same line of behavior is nepotism, parochialism, and things that place family above the other. There's the apocryphal story of the rebel in the time of Stalin, who defied his own father for the regime. When Stalin was presented with this info, Stalin scoffed, "What an idiot, defying his father like that." Here we can see our first signs of dissonance - we are born with a very large weight applied to family, and I think we can all see the immediate, primal benefits of that. In reality, now, the world is different, and with it, a needed reassessment of what that goal should really constitute. Of course, I still advocate good treatment of family - but as much as we treat others, perhaps. Therefore, this is a counterexample to doing everything for family. Note that this doesn't discount tit for tat - one of my first salary paychecks is going toward making sure my parents are comfortable - only because they've provided for me in years past.
	</p>
	<p>
		With the two most generic, arguably naive, intuitions out of the way (happiness optimization and child rearing), we can now focus on what is beyond the fold of normal live-and-die. Already I know things are controversial, but hopefully I've made my point. Half the joy of children is feeling good that someone looks up to you. Any thing other than that and I can imagine some solemn sadness. Inherently, this is selfish, which checks right out. I'm still going to have children if my spouse wills it, and I'm still going to be a wonderful father in as much capacity as I can. Though, there is more. With only one life here, more concretely at 80 years, maybe less, the reasonable thing to do, I conclude, is make something magnificent for the universe. I won't even limit this to us humans.
	</p>
	<p>
		Now that I've put my current philosophy into words, let me describe it in practice. I dont think I will ever behaviorally be able to commit all time to living a life toward something solely magnificent. I enjoy food. I enjoy sleep, and I enjoy the usual things people enjoy. But the traditional career is the main way and use of time to put toward something amazing. Already I've leaned toward artificial intelligence for this. These days, I question the nature of work, though I am in support of a market. My main ambition is to use artificial intelligence to be akin to hygiene and medicine. Let me clarify. Electricity was a great invention, although, as a result we are working longer hours and toil for more of our lives. We have risen people out of poverty with electricity, true. But compare it to hygiene - hygiene is asymmetric in the way that it increases lifespan and flatly just makes life less sufferable, other than the results of the superbacteria treadmill. For the most part though, hygiene has brought humanity into an age of recreation and longer times and stages to enjoy life. In this way, I want AI to become the liberator, not the escalator. While increasing jobs is still a pillar of most governments' administrations, we need to think of better ways to make this possible.
	</p>
	<p>
		I don't believe in universal basic income. I foresee some lapses of transitivity with that. We need to take human nature into account - which says that even if everyone has parity in subsistence, suffering will still come with disparity in status, where people who work more will still garner the ire of those who choose to lounge. And possibly vice-versa. In this way, I think the only path to pave with AI as its blazer is changing payment systems to majorly account for percentages of income rather than absolute values. This aligns with the human mechanism of marginal value. There can be vendors that still accept absolute amounts, for a capitalistic preservation. But many places should take percentage payments. This is now doable due to the virtually impenetrable ledger technologies such as the blockchain - to keep track of amounts in transparency. And yes, this will take an amount of transparency. It's a thought for now, with kinks to be ironed out, but a thought to remember nonetheless.
	</p>
	<p>
		Back to my main goal - creating a proof to best work towards the elements of life I wish to fulfill. For creating something amazing, I need to get past my computer science education, which will certainly free up avenues for me to create in the most robust currency possible - technological (and thus social) capital. My neuroscience education has already scaffolded me with a growing framework of thinking from an 'experience-first' model of thinking. Note that this doesn't mean 'reality distortion', because I believe all experiences eventually regress to one reality. Thus, experience is grounded in reality, and is not manipulable, which still accounts for the sensations of virtual reality et al, but from a brain-centric point-of-view. This is an assumption of faith, which is supportable enough by math and physics, and thus the operation of human brains.
	</p>
	<p>
		First thing we need to do before designing a world is catering to it and know which problems are strong and need to be quelled. First world hunger: by no means a claim to panacaea, I look forward to Musk's BFR intraplanetary infrastructure, in which, with enough capital, I will create a service to send excess food from buffets and homes to hungry countries within 30 minutes. Note, financials need to be worked out more - maybe it can be a work of charity and donation. It would fix a lot - to be profitable would fix even more, as we all know. 
	</p>
	<p>
		Second, we need to go inside the brain to fix Alzheimer's and other neurodeteriorative diseases. This is tough. Maybe, just maybe, AI alongside growing resolution of brainscanning will provide the tipping point needed to map and eradicate these ailments once and for all. Tipping points are important here - and it's what I'm riding on. History has no shortage of them, and the last two decades have had them in fair abundance as well. Tipping points are necessary to create large windfalls where progress once thought to take thousands of years turns into hundreds, and hunreds, dozens. Without this, I'm afraid I will die well before seeing any big progress, even if I were to work at full blast. Even so, believing in tipping points is essential for reaching them, by and large. 
	</p>
	<p>
		Alright, so I need capital. My family household does not make that much yearly. My couple dozen thousand USD investment should pay back in full within 5-10 years if all goes well, and if I actually work as learning valuable engineering skills. That means at least $100K in capital by 32. That's already pretty old by pretty-boy Zuckerberg standards. So maybe in these years, a steady stream of sideprojects can provide opportunity for punctual windfalls which will build momentum toward greater projects. To do this, I need to spend each weekend and homework free night wisely. I believe I can make something useful that nets me at least $12K per year, and I can franchise in this way. 
	</p>
	<p>
		To the point of spending time wisely: this means, especially in New York, to spend less time on YouTube, in bars, and in games. I can't make much warm excuse in the way of relationships - I must maintain those to maintain the human caringness I value. Loneliness is an easy dish for learning, but also with equal capacity for incapacitation. And this goes for both parties always, especially if longterm, genuine, and magical, as love often is described to be. I must wake up every morning early, just a habit really, and nap strategically to clear adenosine and healthily make way for low doses of caffeine. I will not have bags under my eyes. I need to optimize sleep, which means optimizing temperature, noise, security, and light. The more I think of it, a tree would make a very good attack tree to chip away at this life-large problem. 
	</p>
	<p>
		To optimize temperature - most university buildings are temperature controlled. Feet need to be cold to invoke the frozen lobster effect (hereby coined), so no socks. This socially means cleanliness. Bringing alcohol sanitizer to clean biologically without need for a large shower. Keeping hygiene tools always on-the-go, which I already do as of this semester. Eyemasks work faily well for light - though it does reduce the amount of security if sleeping in semi-public places. Since external light cannot always be controlled, it seems security will need to be the one increased, and the eyemask is to stay. Alarms on my backpack are already live. Defensive spray is always available, except for times post-plane, in which I leave sprays at home. Making an infrastructure for tracking each item and periodically requiring check-ins is also doable, and encouraged. More tiles (4 for $50) should ensure that. Keep in mind I make this money by working minimum wage in a restaurant alongside school, and school is afforded by loans, which is afforded by a track record of effort. 
	</p>
	<p>
		The rest I will follow suit in tree form:
	</p>
	<table>
		<tr>
			<td>
				capital - starting now <br>
				Commit to one side project in full a month, accounting for school, work, and other responsibilities. <br>
				To do this, we need a good system for learning how to create things and how to integrate school and other responsibilities into the project so the "penalty of context switching is minimized", and utility, maximized. Additionally, this ensures value, at least to me, and increases the likelihood of value for others, thus justification for any sales. It's a bit late compared to some of the other grandmasters of creation, but I'll take it. Plus, these wouldn't be my first projects, after all.<br>
				Perhaps two hours towards a project per day, with the right Stack Overflow questions for guidance at intervals the next day, will allow for the right pace of progress. 
			</td>
			<td>
				Selling - exposure is the number one indicator of success <br>
				Find out what sells in terms of profiles, etc. If this doesn't exist maybe I will make a crawler myself.
				Will make the rest in notebook.
			</td>
		</tr>
	</table>
</body>
</html>